version: 'latest'
services:
  crud_api:
    restart: always
    build: ./
    command: ./CRUD_API
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    image: postgres:latest

    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
